apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  # labels for deployment. These can be different from pod labels and selector. These are just for deployment identification
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 1
  # selector to identify pods managed by deployment
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: rabbitmq
  # pod template. RS controller uses this to create pods
  template:
    metadata:
      # pod template labels. Should match selector
      labels:
        project: roboshop
        environment: dev
        component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.deployment.imageRepo }}:{{ .Values.deployment.imageVersion }}"
          envFrom:
            - secretRef:
                name: "rabbitmq-creds" 
          imagePullPolicy: Always  # always pulls image from repo. This ensures latest image is used
          # Readiness probe is to check if container is ready to serve traffic. If this fails, pod is removed from service endpoints
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 10   # Pod created, waits for 10 secs, send TCP connection to port 6379
            periodSeconds: 5          # checks readiness every 5 seconds
          # Liveness probe is to check if pod is alive. If this fails, pod is restarted
          livenessProbe:
            tcpSocket:    # check via TCP socket. Just checks if container is listening on specified port
              port: 5672
            initialDelaySeconds: 20   # time to wait before performing first health check
            periodSeconds: 5         # frequency of health checks. Here every 5 seconds
      
---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    component: rabbitmq
  ports:
    - protocol: TCP
      port: 5672    # port on which service is exposed
      targetPort: 5672   # port on which rabbitmq container is listening